services:
  mysql:
    image: 'mysql:8.3.0'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./config.cnf:/etc/mysql/conf.d/config.cnf
#      - ./init-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_USER=counter
      - MYSQL_PASSWORD=counter
      - MYSQL_DATABASE=counter
      - MYSQL_ROOT_PASSWORD=counter
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    container_name: mysql

volumes:
  mysql_data:
    driver: local